### PR TITLE
Update poscheck.py

### PR DESCRIPTION
**Pull request by RyanCarey**
made the decorator return the value of the function.

### CODE REVIEW

**Comment by jeffkaufman** [comment]
Could you add a test that fails before this change but passes after?

**Comment by RyanCarey** [comment]
Sure.

**Review by jeffkaufman — APPROVED** [review]

**Comment by jeffkaufman** [comment]
Thanks!

What's funny is that I got it right in the text inline in https://www.jefftk.com/p/require-keyword-arguments

**Comment by RyanCarey** [comment]
Actually no, it was from copy-pasting that code that I found the
error. To correct it, you need:

def poscheck(f):
      def checked_f(*args, **kwargs):
        if args:
          raise PositionalArgumentsError(f)
        return f(**kwargs)
      return checked_f



Ryan Carey

**Pull request merged**
